services:
  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    command:
      # - --ctx-size
      # - "0"
      # - --predict
      # - "-1"
      - --jinja
      - -m
      - /llm/unsloth/gemma-4-E4B-it-GGUF/gemma-4-E4B-it-UD-Q8_K_XL.gguf
      - --mmproj
      - /llm/unsloth/gemma-4-E4B-it-GGUF/mmproj-F16.gguf
      - --cache-ram
      - "8192"
      # - --log-colors
      - --verbose
      - --port
      - "8080"
      - --host
      - 0.0.0.0
    volumes:
      - /home/tom/llm/:/llm/:ro
    ports:
      - "8080:8080"
    networks:
      - llm_network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
              - gpu

networks:
  llm_network:
    external: true
